name: CI
on: [push]
jobs:
  check-composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer:v2

      - name: Validate composer.json
        run: composer validate

  php-linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - 8.1
          - 8.2
          - 8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: "${{ matrix.php-version }}"

      - name: PHP lint
        run: "find *.php Classes Tests -name '*.php' -print0 | xargs -0 -n 1 -P 4 php -l"

  xml-linting:
    runs-on: ubuntu-latest
    needs: [check-composer]
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: composer:v2

      - name: Install xmllint
        run: sudo apt-get install libxml2-utils

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: PHPUnit configuration file
        run: xmllint --schema vendor/phpunit/phpunit/phpunit.xsd --noout phpunit.xml.dist

      - name: Fetch schema for xliff
        run: wget https://docs.oasis-open.org/xliff/v1.2/os/xliff-core-1.2-strict.xsd --output-document=.Build/xliff-core-1.2-strict.xsd

      - name: TYPO3 language files
        run: xmllint --schema .Build/xliff-core-1.2-strict.xsd --noout $(find Resources -name '*.xlf')

  coding-guideline:
    runs-on: ubuntu-latest
    needs:
      - xml-linting
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer:v2
          php-version: "8.3"

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Coding Guideline
        run: ./vendor/bin/php-cs-fixer fix --dry-run

  phpstan:
    runs-on: ubuntu-latest
    needs:
      - xml-linting
    strategy:
      matrix:
        include:
          - php-version: '8.1'
            typo3-version: '^12.4'
          - php-version: '8.2'
            typo3-version: '^12.4'
          - php-version: '8.3'
            typo3-version: '^12.4'
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"

      - name: Install dependencies
        run: composer req "typo3/cms-core:${{ matrix.typo3-version }}" --prefer-dist --no-progress --no-interaction

      - name: PHPStan
        run: ./vendor/bin/phpstan

  tests:
    runs-on: ubuntu-latest
    needs:
      - xml-linting
    strategy:
      matrix:
        include:
          - php-version: '8.1'
            typo3-version: '^12.4'
          - php-version: '8.2'
            typo3-version: '^12.4'
          - php-version: '8.3'
            typo3-version: '^12.4'
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: composer:v2
          php-version: "${{ matrix.php-version }}"

      - name: Install dependencies
        run: composer req "typo3/cms-core:${{ matrix.typo3-version }}" --prefer-dist --no-progress --no-interaction

      - name: PHPUnit Tests
        run: ./vendor/bin/phpunit --testdox
